### ISSUE TITLE
Latest release totally broken

### ISSUE THREAD

**Issue by taylorotwell** [padraic/mockery#1394]
### Mockery Version

1.6.8

### PHP Version

PHP 8.2

### Issue Description

Latest release of Mockery morning severely breaks Laravel test suite. Wouldn't expect this on a patch release. Can it be reverted?

https://github.com/laravel/framework/actions/runs/8249377959/job/22561635869

**Comment by mfn** [comment]
Can confirm, tested the latest version on a private project, lots of failed tests, similar as shown in https://github.com/laravel/framework/actions/runs/8249377959/job/22561635869#step:8:178

**Comment by ghostwriter** [comment]
Sorry about that… checking now.

**Comment by taylorotwell** [comment]
Thanks!

**Comment by sakarikl** [comment]
Expectation check became more strict. For us it was expected array keys order and string / int mismatches.

**Comment by ghostwriter** [comment]
Pushed a new tag `1.6.9`, pointing to the previous tag/commit `1.6.7`.

Please let me know if it resolves this issue and if there is anything else i need to do from my end.

**Comment by taylorotwell** [comment]
Thanks - we'll take a look a bit later today.

**Comment by seyfahni** [comment]
Just as an additional note, I have a class `Deliverable` that defines the `__set` method. The test fails during the `\Mockery::mock(...)` call because `__set` of the mocked class calls a method, causing it to fail with
```
Mockery\Exception\BadMethodCallException: Received Mockery_5_App_Models_MyModel::setAttribute(), but no expectations were specified

/var/www/service/vendor/illuminate/database/Eloquent/Model.php:1539
/var/www/service/vendor/mockery/mockery/library/Mockery/Container.php:398
/var/www/service/vendor/mockery/mockery/library/Mockery.php:477
/var/www/service/tests/Services/Delivery/Dependency/ActionDependencyErrorTest.php:21
```

This might be the main cause of the breakages...

Edit: I can also confirm that `1.6.9` works again. Thank you very much for the fast response!

**Comment by mfn** [comment]
@ghostwriter can confirm, works for me, thank you 🫡

**Comment by mfn** [comment]
Let me know if you need testers for a new release with the changes you intended.

I mean, testing Laravel is easy, you can probably fork it, switch to your dev version in composer.json and see if it works.

I can also offer running it on a private code base (20k+ tests, lots-o-mockery) and see how it goes, if you let me know which version to test.

**Comment by driesvints** [comment]
1.6.9 resolved the issues for us at Laravel btw. Thanks!

**Comment by ghostwriter** [comment]
Hey everyone,

we were able to test a fix for this issue in #1396 and it is now merged into `1.6.x` branch.

To test this branch, 

you can use `composer require mockery/mockery:1.6.x-dev --dev`

or you can manually include the following in your `composer.json` file:

```
"require-dev": {
    "mockery/mockery":"1.6.x-dev"
}
```

And then run `composer update` to fetch the latest changes from the `1.6.x` branch.

Please let me know if there are any issues when you run your tests.

I will wait for your feedback before creating the next `1.6.10` tag.

Thanks

**Comment by driesvints** [comment]
Hi @ghostwriter. Looks like all tests pass for us! https://github.com/laravel/framework/pull/50643

**Comment by seyfahni** [comment]
I can confirm as well that all my tests work with that version.

**Comment by icemouton** [comment]
Not to be the guy that re-opens a seemingly fixed issue, but since my issue is so similar in context I believe this is the  place to report this.

Ever since 1.6.8 all my test suite fails. If I revert to 1.6.7 everything is fine.

On 1.6.8-1.6.11 I get multiple times this error :

`Mockery\Exception\BadMethodCallException: Received Mockery_32_VMU_FileUpload::__construct(), but no expectations were specified`

For each of my mocks used. 

Is this an intended change ? Do I now need to set an expectation for __construct ? That seems a bit excessive and counter-productive.
