### ISSUE TITLE
shouldIgnoreMissing() not working on instance mocks

### ISSUE THREAD

**Issue by david0** [padraic/mockery#177]
`shouldIgnoreMissing()` does not work on mock objects created using instance mocks.

```php
$m = m::mock('overload:A');
$m->shouldIgnoreMissing();

$a = new A();
$a->doSomething();
```
leads to 
`BadMethodCallException: Method ::doSomething() does not exist on this mock object`

I think it this function would be pretty useful, especially for instance mock objects. Also it looks a little inconsistent, since one can set expectations using `shouldReceive` on all instances, but `shouldIgnoreMissing` only affects the current mock object.

**Comment by robertbasic** [comment]
`shouldIgnoreMissing` and `shouldDeferMissing` (and other such flags present and future) do work, but not on the mock, but on the instance mock.

Sounds confusing, but it's because of internals.

When you do a `m::mock('overload:Foo');` mockery goes and creates a new class called `Foo` based on the `Mock.php` "template". And that template has the `_mockery_ignoreMissing` flag set to `false` by default.

Once the `mock` method gets to the end, it creates an overloaded `Foo` object and returns it to us. The overloaded `Foo` class is also available to instantiate new `Foo` objects.

Calling `$m->shouldIgnoreMissing()` sets the ignore missing flag on the object that was returned by the `mock` method.

Calling `new Foo()` creates a new instance of the `Foo` object that has the `Mock.php` templates default of `false` for `_mockery_ignoreMissing`.

If you want the flag set to `true` on the new instance, you need to call `shouldIgnoreMissing()` on that instance, and not on `$m`.

Obviously this is far from perfect.

One idea I have is to have a global configuration for this, I have a proof of concept in this commit https://github.com/robertbasic/mockery/commit/32d70b7463a83bcac7338a1bc6a0d5a6da1cb469

Thoughts?

/ping @padraic

**Comment by padraic** [comment]
@davedevelopment Thoughts?

See how well I can delegate? :laughing:

**Comment by davedevelopment** [comment]
When you do a `new ClassThatHasBeenOverloaded`, we have a [miracle constructor](https://github.com/padraic/mockery/blob/master/library/Mockery/Generator/StringManipulation/Pass/InstanceMockPass.php#L30) that copies the expectations over from the `master` object, we should probably copy over the relevant flags as well?

**Comment by robertbasic** [comment]
Hm I was looking in there, but didn't see anything useful. Will try again that then.

**Comment by davedevelopment** [comment]
This is a complete hack and I haven't tested it, but should work in theory

```
diff --git a/library/Mockery/Generator/StringManipulation/Pass/InstanceMockPass.php b/library/Mockery/Generator/StringManipulation/Pass/InstanceMockPass.php
index ec370f3..e3bbf7d 100644
--- a/library/Mockery/Generator/StringManipulation/Pass/InstanceMockPass.php
+++ b/library/Mockery/Generator/StringManipulation/Pass/InstanceMockPass.php
@@ -14,6 +14,13 @@ class InstanceMockPass
     {
         \$this->_mockery_ignoreVerification = false;
         \$associatedRealObject = \Mockery::fetchMock(__CLASS__);
+
+        foreach (get_object_vars(\$this) as \$attr => \$val) {
+            if (\$attr !== "_mockery_ignoreVerification" && \$attr !== "_mockery_expectations") {
+                \$this->\$attr = \$associatedRealObject->\$attr;
+            }
+        }
+
         \$directors = \$associatedRealObject->mockery_getExpectations();
         foreach (\$directors as \$method=>\$director) {
             \$expectations = \$director->getExpectations();
```

**Comment by robertbasic** [comment]
@davedevelopment pull request was merged, ticket can be closed?
