### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by ruudk** [padraic/mockery#561]
I really want to use the latest stuff (PHP 7 support) from master. 

0.9.4 is the latest release and is from april 2, 2015.

**Comment by davedevelopment** [comment]
We're a little in limbo at the minute, the master branch is what will be 1.0, which are I aren't going to be tagging just yet. I'd suggest just using the master branch as is for now. Tagging another 0.9.x release would be little different.

**Comment by michaelmoussa** [comment]
@davedevelopment another 0.9.x release would be very helpful, actually. :)

We've been running with `"mockery/mockery": "dev-master#971dcdfdc2239b3d516672139f4368c19f6c2060 as 0.9.5"` for 3 or 4 months, since that's the commit that added support for scalar typehints and return types, and we're on PHP 7. Would be nice to be able to just specify `^0.9.5`.

**Comment by GrahamCampbell** [comment]
> @davedevelopment another 0.9.x release would be very helpful, actually. :)

That won't be possible because of the breaking changes.

**Comment by GrahamCampbell** [comment]
The next has to bump the minor/major vesion.

**Comment by michaelmoussa** [comment]
`0.10.0` would be fine too.

**Comment by GrahamCampbell** [comment]
But it was promised that there would never be a 0.10.0 release. The next would be 1.0.0.

**Comment by michaelmoussa** [comment]
I was not aware of that, but consider that there hasn't been a new release in nearly a year. As a long-time user and advocate of Mockery, I think I would prefer a `0.10.0` release for PHP 7 compatibility over an indeterminate `1.0.0` release date, wouldn't you?

SemVer _does_ allow for BC breaks in major version zero. Besides, Mockery is a dev dependency, not a Production. The BC break (which, again, is allowed by SemVer), is unlikely to unexpectedly break any Production systems because it's not a library that one is expected to use in Production anyway.

**Comment by davedevelopment** [comment]
If someone wants to create a branch off 0.9.4 and back port the relevant commits, I'm happy to tag a release, I don't currently have the time.

**Comment by michaelmoussa** [comment]
@davedevelopment I'm happy to do this, but I can't create branches on this repo. Do you want to create that initial branch off of 0.9.4, and I'll send a PR to it with the relevant cherry-picked commits? Maybe call it `php7-compat` or something...?

**Comment by mvdstam** [comment]
👍  Please tag `0.9.5` if possible.

**Comment by nicwortel** [comment]
Any progress on this? A 0.10.0 version would be nice. As @michaelmoussa explains, it could contain BC breaks.

**Comment by davedevelopment** [comment]
@michaelmoussa sorry for not replying, missed this. I've just created a 0.9 branch which you can send a PR to

**Comment by michaelmoussa** [comment]
@davedevelopment done. See #596

**Comment by prisis** [comment]
How long will it take to tag a new release with php7 support?

**Comment by davedevelopment** [comment]
@prisis soon I think, @michaelmoussa has done the hard work in #596, just need to get the build passing and I'll merge and tag.

**Comment by michaelmoussa** [comment]
@davedevelopment I'm traveling and without a computer so if you wouldn't mind replacing that `[]` with `array` that'd be great.

The build is complaining about a -0.6% coverage change as well by the way, but all I've done is cherry-picked commits that had already been merged into `master` months ago.

**Comment by davedevelopment** [comment]
Done - https://github.com/padraic/mockery/releases/tag/0.9.5

Thanks go to @michaelmoussa
